### ISSUE TITLE
Using assert lib decrease my code coverage

### ISSUE THREAD

**Issue by humbertoc-silva** [anderseknert/rego-test-assertions#4]
Hi,

I am using the assert lib in my unit tests, and it is helpful but when I run my OPA CI, my code coverage score decreases a lot because I do not have any unit test related to the assert lib. My policies have 100% code coverage but it decreases to 58% because of this situation.

I saw that we have a test file but it is used as an example instead of a test suite.

How can we resolve this? Maybe creating a test suite and importing it into the projects? Do we have some other options?

Thank you.

**Comment by anderseknert** [comment]
Hi Humberto! Hmm, that's interesting :) The tests here aren't really meant to be run programmatically, but require someone to look at the actual output to verify they're being printed. I had not considered the coverage situation you describe :) I'll see if there's something I can do to fix that.

**Comment by humbertoc-silva** [comment]
Ok, Anders. Let me know if there is something that I can do to help you.

**Comment by anderseknert** [comment]
Fixed now! I took the opportunity to modernize the policy somewhat as well, which means it'll now require OPA v0.59.0+. I hope that works for your use case.

**Comment by humbertoc-silva** [comment]
Thank you, Anders. I will test the new version next week and give you feedback.

**Comment by humbertoc-silva** [comment]
Hi @anderseknert,
I did my tests and now everything is working, thank you.

**Comment by anderseknert** [comment]
Happy to hear that @humbertoc-silva 👍
